name: MindForger macOS build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt 5 + ccache
        run: brew install qt@5 ccache

      - name: Force link Qt
        run: brew link qt@5 --force

      - name: Build dependency: cmark-gfm
        run: cd deps/cmark-gfm && mkdir -v build && cd build && cmake -DCMARK_TESTS=OFF -DCMARK_SHARED=OFF .. && cmake --build .

      - name: Run QMake
        run: pwd ; qmake -r "CONFIG+=mfci" mindforger.pro 

      - name: Run Make
        run: make -j 4

      - name: Deploy
        run: pwd
